on: [push]

name: Node.js

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'

      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build
          rm -rf node_modules
          npm install --production
          echo "AUTHORIZATION=${{secrets.AUTHORIZATION}}" >> .env
        env:
          PORT: 8080

      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'vocaloid-karaoke-ranking'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
